package state

import "github.com/ishii1648/codex-issue-loop/internal/domain/statecontract"

type SemanticViolation = statecontract.SemanticViolation
type SemanticCompatibilityError = statecontract.SemanticCompatibilityError

const SemanticCodeCompatible = statecontract.SemanticCodeCompatible
const SemanticCodeContractVersionMismatch = statecontract.SemanticCodeContractVersionMismatch
const SemanticCodeWorkspaceProvenanceMissing = statecontract.SemanticCodeWorkspaceProvenanceMissing
const SemanticCodeWorkspaceProvenanceInvalid = statecontract.SemanticCodeWorkspaceProvenanceInvalid
const SemanticCodeExecutionAuthorityMissing = statecontract.SemanticCodeExecutionAuthorityMissing
const SemanticCodePreparedTransactionPresent = statecontract.SemanticCodePreparedTransactionPresent

func ValidateSemanticContract(snapshot Snapshot) error {
	return statecontract.ValidateSemanticContract(snapshot)
}

func SemanticViolations(snapshot Snapshot) []SemanticViolation {
	return statecontract.SemanticViolations(snapshot)
}
